name: Spider

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 5.0.100-preview.7.20366.6
          
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - uses: robinraju/release-downloader@v1
        with:
          repository: "leibnitz27/cfr"
          tag: '0.150'
          fileName: 'cfr-0.150.jar'
          out-file-path: "./tools/"
      

      - name: Build spider
        run: dotnet publish .\src\Spider\Spider.csproj -o ./ -r win-x64 -p:PublishSingleFile=true
        
      - name: Run spider
        run: .\Spider
          
        shell: pwsh
        env:
          token: ${{ Secrets.my_token }}
