name: Spider

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
    
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - uses: robinraju/release-downloader@v1
        with:
          repository: "leibnitz27/cfr"
          tag: '0.150'
          fileName: 'cfr-0.150.jar'
          out-file-path: "./tools/"
      
      - name: Run spider
        run: |
          dotnet publish .\src\Spider\Spider.csproj -o ./ -r win-x64 -p:PublishSingleFile=true
          .\Spider
        shell: pwsh
        env:
          token: ${{ Secrets.my_token }}
